name: cicd-workflow
on: workflow_dispatch
jobs:
  ci-call:
    uses: arif511basha/mci/.github/workflows/ci.yml@main

  cd-call:
    needs: ci-call
    uses: arif511basha/mcd/.github/workflows/cd.yml@main


       
